name: Unit test for ARM
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
jobs:
  lint:
    if: github.repository == 'scikit-learn/scikit-learn'
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.12'
      - name: Install linters
        run: 'source build_tools/shared.sh

          # Include pytest compatibility with mypy

          pip install pytest $(get_dep ruff min) $(get_dep mypy min) $(get_dep black
          min) cython-lint

          '
      - id: measurement-4
        name: Record Measurement After Install linters
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install linters
          task: get-measurement
      - name: Run linters
        run: ./build_tools/linting.sh
      - id: measurement-6
        name: Record Measurement After Run linters
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run linters
          task: get-measurement
      - name: Run Meson OpenMP checks
        run: 'pip install ninja meson scipy

          python build_tools/check-meson-openmp-dependencies.py

          '
      - id: measurement-8
        name: Record Measurement After Run Meson OpenMP checks
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run Meson OpenMP checks
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  run-unit-tests:
    if: github.repository == 'scikit-learn/scikit-learn'
    name: Run unit tests
    needs:
      - lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          environment-file: build_tools/github/pymin_conda_forge_arm_linux-aarch64_conda.lock
          environment-name: ci
      - name: Build and run tests
        run: bash build_tools/github/build_test_arm.sh
        shell: bash -el {0}
      - id: measurement-4
        name: Record Measurement After Build and run tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build and run tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  contents: read
