name: Assign
on:
  push:
    branches:
      - main

jobs:
  one:
    if: startsWith(github.event.comment.body, '/take') && !github.event.issue.assignee
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - env:
          GH_TOKEN: ${{ github.token }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: "# Using REST API directly because assigning through gh has some severe\
          \ limitations. For more details, see\n# https://github.com/scikit-learn/scikit-learn/issues/29395#issuecomment-2206776963\n\
          echo \"Assigning issue ${{ github.event.issue.number }} to ${{ github.event.comment.user.login\
          \ }}\"\ncurl -H \"Authorization: token $GH_TOKEN\" -d '{\"assignees\": [\"\
          ${{ github.event.comment.user.login }}\"]}' \\\n    https://api.github.com/repos/${{\
          \ github.repository }}/issues/${{ github.event.issue.number }}/assignees\n\
          gh issue edit $ISSUE --remove-label \"help wanted\"\n"
      - id: measurement-2
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Step
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  issues: write
