name: Check Changelog
on:
  push:
    branches:
      - main

jobs:
  check:
    name: A reviewer will let you know if it is required or can be bypassed
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - id: tests_changed
        name: Check if tests have changed
        run: "set -xe\nchanged_files=$(git diff --name-only origin/main)\n# Changelog\
          \ should be updated only if tests have been modified\nif [[ \"$changed_files\"\
          \ =~ tests ]]\nthen\n  echo \"check_changelog=true\" >> $GITHUB_OUTPUT\n\
          fi\n"
      - id: measurement-3
        name: Record Measurement After Check if tests have changed
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check if tests have changed
          task: get-measurement
      - env:
          BOT_USERNAME: changelog-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.tests_changed.outputs.check_changelog == 'true'
        name: Check changelog entry
        uses: scientific-python/action-towncrier-changelog@v1
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  contents: read
