name: linter
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
jobs:
  comment:
    if: ${{ !cancelled() }}
    needs: lint
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python -m pip install requests
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - id: download-artifact
        name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lint-log
      - name: Print log
        run: cat linting_output.txt
      - id: measurement-7
        name: Record Measurement After Print log
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Print log
          task: get-measurement
      - env:
          BRANCH_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_FILE: linting_output.txt
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RUN_ID: ${{ github.run_id }}
          VERSIONS_FILE: versions.txt
        id: process-comments
        name: Process Comments
        run: python ./build_tools/get_comment.py
      - id: measurement-9
        name: Record Measurement After Process Comments
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Process Comments
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  lint:
    permissions:
      pull-requests: none
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: 'curl https://raw.githubusercontent.com/${{ github.repository }}/main/build_tools/shared.sh
          --retry 5 -o ./build_tools/shared.sh

          source build_tools/shared.sh

          # Include pytest compatibility with mypy

          pip install pytest $(get_dep ruff min) $(get_dep mypy min) $(get_dep black
          min) cython-lint

          # we save the versions of the linters to be used in the error message later.

          python -c "from importlib.metadata import version; print(f\"ruff={version(''ruff'')}\")"
          >> /tmp/versions.txt

          python -c "from importlib.metadata import version; print(f\"mypy={version(''mypy'')}\")"
          >> /tmp/versions.txt

          python -c "from importlib.metadata import version; print(f\"black={version(''black'')}\")"
          >> /tmp/versions.txt

          python -c "from importlib.metadata import version; print(f\"cython-lint={version(''cython-lint'')}\")"
          >> /tmp/versions.txt

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - id: lint-script
        name: Run linting
        run: 'curl https://raw.githubusercontent.com/${{ github.repository }}/main/build_tools/linting.sh
          --retry 5 -o ./build_tools/linting.sh

          set +e

          ./build_tools/linting.sh &> /tmp/linting_output.txt

          cat /tmp/linting_output.txt

          '
      - id: measurement-6
        name: Record Measurement After Run linting
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run linting
          task: get-measurement
      - if: always()
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lint-log
          path: '/tmp/linting_output.txt

            /tmp/versions.txt

            '
          retention-days: 1
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
