name: Update tracking issue
on:
  push:
    branches:
      - main

jobs:
  update_tracking_issue:
    if: github.repository == 'scikit-learn/scikit-learn' && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Update tracking issue on GitHub
        run: "set -ex\nif [[ ${{ inputs.job_status }} == \"success\" ]]; then\n  TESTS_PASSED=true\n\
          else\n  TESTS_PASSED=false\nfi\n\npip install defusedxml PyGithub\npython\
          \ maint_tools/update_tracking_issue.py \\\n  ${{ secrets.BOT_GITHUB_TOKEN\
          \ }} \\\n  \"$GITHUB_WORKFLOW\" \\\n  \"$GITHUB_REPOSITORY\" \\\n  https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\
          \ \\\n  --tests-passed $TESTS_PASSED\n"
      - id: measurement-4
        name: Record Measurement After Update tracking issue on GitHub
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Update tracking issue on GitHub
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  contents: read
