name: Update lock files
on:
  push:
    branches:
      - main

jobs:
  update_lock_files:
    if: github.repository == 'scikit-learn/scikit-learn'
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Generate lock files
        run: 'source build_tools/shared.sh

          source $CONDA/bin/activate

          conda install -n base conda conda-libmamba-solver -y

          conda config --set solver libmamba

          conda install -c conda-forge "$(get_dep conda-lock min)" -y


          python build_tools/update_environments_and_lock_files.py ${{ matrix.update_script_args
          }}

          '
      - id: measurement-3
        name: Record Measurement After Generate lock files
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Generate lock files
          task: get-measurement
      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          author: Lock file bot <noreply@github.com>
          body: 'Update lock files.


            ### Note

            If the CI tasks fail, create a new branch based on this PR and add the
            required fixes to that branch.

            '
          branch: auto-update-lock-files-${{ matrix.name }}
          commit-message: Update CI lock files ${{ matrix.additional_commit_message
            }}
          committer: Lock file bot <noreply@github.com>
          delete-branch: true
          push-to-fork: scikit-learn-bot/scikit-learn
          title: ':lock: :robot: CI Update lock files for ${{ matrix.name }} CI build(s)
            :lock: :robot:'
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          PR_NUMBER: ${{steps.cpr.outputs.pull-request-number}}
        if: steps.cpr.outputs.pull-request-number != '' && matrix.name == 'array-api'
        name: Trigger additional tests
        run: "curl -L \\\n  -X POST \\\n  -H \"Accept: application/vnd.github+json\"\
          \ \\\n  -H \"Authorization: Bearer $GH_TOKEN\" \\\n  -H \"X-GitHub-Api-Version:\
          \ 2022-11-28\" \\\n  https://api.github.com/repos/scikit-learn/scikit-learn/issues/$PR_NUMBER/labels\
          \ \\\n  -d '{\"labels\":[\"CUDA CI\"]}'\n"
      - id: measurement-6
        name: Record Measurement After Trigger additional tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Trigger additional tests
          task: get-measurement
      - if: steps.cpr.outputs.pull-request-number != ''
        name: Check Pull Request
        run: 'echo "### :rocket: Pull-Request Summary" >> ${GITHUB_STEP_SUMMARY}

          echo "" >> ${GITHUB_STEP_SUMMARY}

          echo "The following lock files pull-request has been auto-generated:"

          echo "- **PR** #${{ steps.cpr.outputs.pull-request-number }}" >> ${GITHUB_STEP_SUMMARY}

          echo "- **URL** ${{ steps.cpr.outputs.pull-request-url }}" >> ${GITHUB_STEP_SUMMARY}

          echo "- **Operation** [${{ steps.cpr.outputs.pull-request-operation }}]"
          >> ${GITHUB_STEP_SUMMARY}

          echo "- **SHA** ${{ steps.cpr.outputs.pull-request-head-sha }}" >> ${GITHUB_STEP_SUMMARY}

          '
      - id: measurement-8
        name: Record Measurement After Check Pull Request
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check Pull Request
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        include:
          - additional_commit_message: '[doc build]'
            name: main
            update_script_args: --select-tag main-ci
          - additional_commit_message: '[scipy-dev]'
            name: scipy-dev
            update_script_args: --select-tag scipy-dev
          - additional_commit_message: '[free-threaded]'
            name: free-threaded
            update_script_args: --select-tag free-threaded
          - name: array-api
            update_script_args: --select-tag cuda
