name: Wheel builder
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
jobs:
  build_sdist:
    if: needs.check_build_trigger.outputs.build
    name: Source distribution
    needs: check_build_trigger
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout scikit-learn
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Build source distribution
        run: bash build_tools/github/build_source.sh
      - id: measurement-4
        name: Record Measurement After Build source distribution
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build source distribution
          task: get-measurement
      - env:
          SKLEARN_SKIP_NETWORK_TESTS: 1
        name: Test source distribution
        run: bash build_tools/github/test_source.sh
      - id: measurement-6
        name: Record Measurement After Test source distribution
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Test source distribution
          task: get-measurement
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  build_wheels:
    defaults:
      run:
        shell: bash -el {0}
    if: needs.check_build_trigger.outputs.build
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image
      }}
    needs: check_build_trigger
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout scikit-learn
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - if: ${{ startsWith(matrix.platform_id, 'macosx') }}
        uses: conda-incubator/setup-miniconda@v3
      - env:
          CIBW_ARCHS: all
          CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh
            {project}
          CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh
          CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh
            ${{ matrix.python }}
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_BUILD_VERBOSITY: 1
          CIBW_CONFIG_SETTINGS_WINDOWS: setup-args=--vsenv
          CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
          CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
          CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh
            {wheel} {dest_dir}
          CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}
          CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh
            ${{ matrix.python }} {project}
          CIBW_TEST_REQUIRES: pytest pandas
          CIBW_TEST_REQUIRES_WINDOWS: ''
        name: Build and test wheels
        run: bash build_tools/wheels/build_wheels.sh
      - id: measurement-5
        name: Record Measurement After Build and test wheels
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build and test wheels
          task: get-measurement
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
          path: wheelhouse/*.whl
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform_id: win_amd64
            python: 39
          - os: windows-latest
            platform_id: win_amd64
            python: 310
          - os: windows-latest
            platform_id: win_amd64
            python: 311
          - os: windows-latest
            platform_id: win_amd64
            python: 312
          - os: windows-latest
            platform_id: win_amd64
            python: 313
          - free_threaded_support: true
            os: windows-latest
            platform_id: win_amd64
            python: 313t
          - manylinux_image: manylinux2014
            os: ubuntu-latest
            platform_id: manylinux_x86_64
            python: 39
          - manylinux_image: manylinux2014
            os: ubuntu-latest
            platform_id: manylinux_x86_64
            python: 310
          - manylinux_image: manylinux2014
            os: ubuntu-latest
            platform_id: manylinux_x86_64
            python: 311
          - manylinux_image: manylinux2014
            os: ubuntu-latest
            platform_id: manylinux_x86_64
            python: 312
          - manylinux_image: manylinux2014
            os: ubuntu-latest
            platform_id: manylinux_x86_64
            python: 313
          - free_threaded_support: true
            manylinux_image: manylinux2014
            os: ubuntu-latest
            platform_id: manylinux_x86_64
            python: 313t
          - manylinux_image: manylinux2014
            os: ubuntu-24.04-arm
            platform_id: manylinux_aarch64
            python: 39
          - manylinux_image: manylinux2014
            os: ubuntu-24.04-arm
            platform_id: manylinux_aarch64
            python: 310
          - manylinux_image: manylinux2014
            os: ubuntu-24.04-arm
            platform_id: manylinux_aarch64
            python: 311
          - manylinux_image: manylinux2014
            os: ubuntu-24.04-arm
            platform_id: manylinux_aarch64
            python: 312
          - manylinux_image: manylinux2014
            os: ubuntu-24.04-arm
            platform_id: manylinux_aarch64
            python: 313
          - os: macos-13
            platform_id: macosx_x86_64
            python: 39
          - os: macos-13
            platform_id: macosx_x86_64
            python: 310
          - os: macos-13
            platform_id: macosx_x86_64
            python: 311
          - os: macos-13
            platform_id: macosx_x86_64
            python: 312
          - os: macos-13
            platform_id: macosx_x86_64
            python: 313
          - free_threaded_support: true
            os: macos-13
            platform_id: macosx_x86_64
            python: 313t
          - os: macos-14
            platform_id: macosx_arm64
            python: 39
          - os: macos-14
            platform_id: macosx_arm64
            python: 310
          - os: macos-14
            platform_id: macosx_arm64
            python: 311
          - os: macos-14
            platform_id: macosx_arm64
            python: 312
          - os: macos-14
            platform_id: macosx_arm64
            python: 313
          - free_threaded_support: true
            os: macos-14
            platform_id: macosx_arm64
            python: 313t
  check_build_trigger:
    if: github.repository == 'scikit-learn/scikit-learn'
    name: Check build trigger
    outputs:
      build: ${{ steps.check_build_trigger.outputs.build }}
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout scikit-learn
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: check_build_trigger
        name: Check build trigger
        run: bash build_tools/github/check_build_trigger.sh
      - id: measurement-3
        name: Record Measurement After Check build trigger
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check build trigger
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  update-tracker:
    if: ${{ always() }}
    needs:
      - build_wheels
    secrets:
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    uses: ./.github/workflows/update_tracking_issue.yml
    with:
      job_status: ${{ needs.build_wheels.result }}
  upload_anaconda:
    environment: upload_anaconda
    if: github.event_name != 'pull_request'
    name: Upload to Anaconda
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout scikit-learn
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
          pattern: cibw-*
      - name: Setup Python
        uses: actions/setup-python@v5
      - env:
          ARTIFACTS_PATH: dist
          SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN
            }}
          SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN
            }}
        name: Upload artifacts
        run: bash build_tools/github/upload_anaconda.sh
      - id: measurement-5
        name: Record Measurement After Upload artifacts
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Upload artifacts
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  contents: read
